logging:
  path: ./log/
#  level:
#    com.baomidou.dynamic: debug
spring:
  redis:
    host: localhost
#  datasource:
#      url: jdbc:mysql://localhost:3306/xzs?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
#      username: root
#      password: liang0927
#      driver-class-name: com.mysql.jdbc.Driver

  datasource:
    dynamic:
#      master:
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/xzs?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
          username: root
          password: liang0927
          driver-class-name: com.mysql.jdbc.Driver
        slave1:
          url: jdbc:mysql://localhost:3306/xzs01?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
          username: root
          password: liang0927
          driver-class-name: com.mysql.jdbc.Driver
        slave2:
          url: jdbc:mysql://localhost:3306/xzs02?useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
          username: root
          password: liang0927
          driver-class-name: com.mysql.jdbc.Driver






